# Generated by Django 2.2.24 on 2021-08-03 13:18

import app_data.fields
from django.db import migrations, models
import django.db.models.deletion
import hvad.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_news', '0002_auto_20190327_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('aldryn_news.Category', 'aldryn_news.CategoryTranslation'),
        ),
        migrations.AddField(
            model_name='news',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('aldryn_news.News', 'aldryn_news.NewsTranslation'),
        ),
        migrations.AddField(
            model_name='tag',
            name='_hvad_query',
            field=hvad.fields.SingleTranslationObject('aldryn_news.Tag', 'aldryn_news.TagTranslation'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_news.Category'),
        ),
        migrations.AlterField(
            model_name='newstranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_news.News'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aldryn_news_taggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
        migrations.AlterField(
            model_name='tagtranslation',
            name='master',
            field=hvad.fields.MasterKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='aldryn_news.Tag'),
        ),
        migrations.CreateModel(
            name='NewsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
                ('paginate_by', models.PositiveIntegerField(default=5, verbose_name='Paginate size')),
                ('namespace', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Instance namespace')),
            ],
            options={
                'verbose_name': 'Apphook config',
                'verbose_name_plural': 'Apphook configs',
                'abstract': False,
                'unique_together': {('type', 'namespace')},
            },
        ),
    ]
